name: CI - Validate Website

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Validate HTML
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: .
        log_level: INFO
        css: true
        file_types: html
        
    - name: Check for broken links
      uses: lycheeverse/lychee-action@v1.9.1
      with:
        args: --verbose --no-progress './**/*.html' './**/*.md'
        fail: false  # Don't fail the build on broken links, just report them
        
    - name: Upload link check results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: link-check-results
        path: lychee/out.md
        
    - name: Check file sizes
      run: |
        echo "Checking large files..."
        find . -type f -size +1M -exec ls -lh {} \; | grep -v ".git"
        
    - name: Validate JSON files
      run: |
        for file in $(find . -name "*.json" -not -path "./node_modules/*" -not -path "./.git/*"); do
          echo "Validating $file"
          python -m json.tool "$file" > /dev/null || echo "Invalid JSON in $file"
        done